language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install -e ."
script:
    - "nosetests tests"
